/// Flutter icons Covid
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Covid
///      fonts:
///       - asset: fonts/Covid.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class Covid {
  Covid._();

  static const _kFontFam = "Covid";
  // static const String? _kFontPkg = null;

  static const IconData lungs_virus = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData virus_slash = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData head_side_mask =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData head_side_cough_slash =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData head_side_cough =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData handshake_slash =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData people_arrows = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pump_soap = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData pump_medical = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData bone_bite = IconData(0xe938, fontFamily: _kFontFam);
}
